FROM python:3.10

# Set working directory
WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy pip files
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy

# Copy project files
COPY . .

# Expose Django port
EXPOSE 8000

# Run Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]